version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: Europe/Berlin
      allow:
      - dependency-type: 'production'
    assignees:
    - DutchmanNL
    target-branch: "dependencyAutoUpdate"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
    versioning-strategy: increase
