# Dependabot will run on day 2 of each month at 01:05 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
      allow:
        - dependency-type: "production"
    assignees:
      - "DutchmanNL"
    target-branch: "dependencyAutoUpdate"
    labels:
      - "npm dependencies"
    versioning-strategy: "increase"
    open-pull-requests-limit: 15
