/*global systemDictionary:true */
'use strict';

systemDictionary = {
	"Countries": {
		"en": "Countries",
		"de": "Länder",
		"ru": "Страны",
		"pt": "Países",
		"nl": "Landen",
		"fr": "Des pays",
		"it": "Paesi",
		"es": "Países",
		"pl": "Kraje",
		"zh-cn": "国别"
	},
	"China": {
		"en": "China",
		"de": "China",
		"ru": "Китай",
		"pt": "China",
		"nl": "China",
		"fr": "Chine",
		"it": "Cina",
		"es": "China",
		"pl": "Chiny",
		"zh-cn": "中国"
	},
	"Italy": {
		"en": "Italy",
		"de": "Italien",
		"ru": "Италия",
		"pt": "Itália",
		"nl": "Italië",
		"fr": "Italie",
		"it": "Italia",
		"es": "Italia",
		"pl": "Włochy",
		"zh-cn": "意大利"
	},
	"Spain": {
		"en": "Spain",
		"de": "Spanien",
		"ru": "Испания",
		"pt": "Espanha",
		"nl": "Spanje",
		"fr": "Espagne",
		"it": "Spagna",
		"es": "España",
		"pl": "Hiszpania",
		"zh-cn": "西班牙"
	},
	"USA": {
		"en": "USA",
		"de": "USA",
		"ru": "США",
		"pt": "EUA",
		"nl": "Verenigde Staten van Amerika",
		"fr": "Etats-Unis",
		"it": "Stati Uniti d'America",
		"es": "Estados Unidos",
		"pl": "USA",
		"zh-cn": "美国"
	},
	"Germany": {
		"en": "Germany",
		"de": "Deutschland",
		"ru": "Германия",
		"pt": "Alemanha",
		"nl": "Duitsland",
		"fr": "Allemagne",
		"it": "Germania",
		"es": "Alemania",
		"pl": "Niemcy",
		"zh-cn": "德国"
	},
	"Iran": {
		"en": "Iran",
		"de": "Ich rannte",
		"ru": "Иран",
		"pt": "Eu corri",
		"nl": "Ik rende",
		"fr": "J'ai couru",
		"it": "Mi sono imbattuto",
		"es": "Corrí",
		"pl": "Iran",
		"zh-cn": "伊朗"
	},
	"France": {
		"en": "France",
		"de": "Frankreich",
		"ru": "Франция",
		"pt": "França",
		"nl": "Frankrijk",
		"fr": "France",
		"it": "Francia",
		"es": "Francia",
		"pl": "Francja",
		"zh-cn": "法国"
	},
	"S. Korea": {
		"en": "S. Korea",
		"de": "Südkorea",
		"ru": "Южная Корея",
		"pt": "Coreia do Sul",
		"nl": "Zuid-Korea",
		"fr": "Corée du Sud",
		"it": "Corea del Sud",
		"es": "Corea del Sur",
		"pl": "S. Korea",
		"zh-cn": "韩国"
	},
	"Switzerland": {
		"en": "Switzerland",
		"de": "Schweiz",
		"ru": "Швейцария",
		"pt": "Suíça",
		"nl": "Zwitserland",
		"fr": "Suisse",
		"it": "Svizzera",
		"es": "Suiza",
		"pl": "Szwajcaria",
		"zh-cn": "瑞士"
	},
	"UK": {
		"en": "UK",
		"de": "Vereinigtes Königreich",
		"ru": "Великобритания",
		"pt": "Reino Unido",
		"nl": "UK",
		"fr": "Royaume-Uni",
		"it": "UK",
		"es": "Reino Unido",
		"pl": "UK",
		"zh-cn": "英国"
	},
	"Netherlands": {
		"en": "Netherlands",
		"de": "Niederlande",
		"ru": "Нидерланды",
		"pt": "Países Baixos",
		"nl": "Nederland",
		"fr": "Pays-Bas",
		"it": "Olanda",
		"es": "Países Bajos",
		"pl": "Holandia",
		"zh-cn": "荷兰"
	},
	"Belgium": {
		"en": "Belgium",
		"de": "Belgien",
		"ru": "Бельгия",
		"pt": "Bélgica",
		"nl": "België",
		"fr": "Belgique",
		"it": "Belgio",
		"es": "Bélgica",
		"pl": "Belgia",
		"zh-cn": "比利时"
	},
	"Austria": {
		"en": "Austria",
		"de": "Österreich",
		"ru": "Австрия",
		"pt": "Áustria",
		"nl": "Oostenrijk",
		"fr": "L'Autriche",
		"it": "Austria",
		"es": "Austria",
		"pl": "Austria",
		"zh-cn": "奥地利"
	},
	"Norway": {
		"en": "Norway",
		"de": "Norwegen",
		"ru": "Норвегия",
		"pt": "Noruega",
		"nl": "Noorwegen",
		"fr": "Norvège",
		"it": "Norvegia",
		"es": "Noruega",
		"pl": "Norwegia",
		"zh-cn": "挪威"
	},
	"Sweden": {
		"en": "Sweden",
		"de": "Schweden",
		"ru": "Швеция",
		"pt": "Suécia",
		"nl": "Zweden",
		"fr": "Suède",
		"it": "Svezia",
		"es": "Suecia",
		"pl": "Szwecja",
		"zh-cn": "瑞典"
	},
	"Portugal": {
		"en": "Portugal",
		"de": "Portugal",
		"ru": "Португалия",
		"pt": "Portugal",
		"nl": "Portugal",
		"fr": "le Portugal",
		"it": "Portogallo",
		"es": "Portugal",
		"pl": "Portugalia",
		"zh-cn": "葡萄牙"
	},
	"Denmark": {
		"en": "Denmark",
		"de": "Dänemark",
		"ru": "Дания",
		"pt": "Dinamarca",
		"nl": "Denemarken",
		"fr": "Danemark",
		"it": "Danimarca",
		"es": "Dinamarca",
		"pl": "Dania",
		"zh-cn": "丹麦"
	},
	"Australia": {
		"en": "Australia",
		"de": "Australien",
		"ru": "Австралия",
		"pt": "Austrália",
		"nl": "Australië",
		"fr": "Australie",
		"it": "Australia",
		"es": "Australia",
		"pl": "Australia",
		"zh-cn": "澳大利亚"
	},
	"Canada": {
		"en": "Canada",
		"de": "Kanada",
		"ru": "Канада",
		"pt": "Canadá",
		"nl": "Canada",
		"fr": "Canada",
		"it": "Canada",
		"es": "Canadá",
		"pl": "Kanada",
		"zh-cn": "加拿大"
	},
	"Malaysia": {
		"en": "Malaysia",
		"de": "Malaysia",
		"ru": "Малайзия",
		"pt": "Malásia",
		"nl": "Maleisië",
		"fr": "Malaisie",
		"it": "Malaysia",
		"es": "Malasia",
		"pl": "Malezja",
		"zh-cn": "马来西亚"
	},
	"Brazil": {
		"en": "Brazil",
		"de": "Brasilien",
		"ru": "Бразилия",
		"pt": "Brasil",
		"nl": "Brazilië",
		"fr": "Brésil",
		"it": "Brasile",
		"es": "Brasil",
		"pl": "Brazylia",
		"zh-cn": "巴西"
	},
	"Japan": {
		"en": "Japan",
		"de": "Japan",
		"ru": "Япония",
		"pt": "Japão",
		"nl": "Japan",
		"fr": "Japon",
		"it": "Giappone",
		"es": "Japón",
		"pl": "Japonia",
		"zh-cn": "日本"
	},
	"Czechia": {
		"en": "Czechia",
		"de": "Tschechien",
		"ru": "Чехия",
		"pt": "Czechia",
		"nl": "Tsjechië",
		"fr": "Tchéquie",
		"it": "Repubblica Ceca",
		"es": "Chequia",
		"pl": "Czechy",
		"zh-cn": "捷克语"
	},
	"Turkey": {
		"en": "Turkey",
		"de": "Truthahn",
		"ru": "индейка",
		"pt": "Peru",
		"nl": "kalkoen",
		"fr": "dinde",
		"it": "tacchino",
		"es": "pavo",
		"pl": "indyk",
		"zh-cn": "火鸡"
	},
	"Israel": {
		"en": "Israel",
		"de": "Israel",
		"ru": "Израиль",
		"pt": "Israel",
		"nl": "Israël",
		"fr": "Israël",
		"it": "Israele",
		"es": "Israel",
		"pl": "Izrael",
		"zh-cn": "以色列"
	},
	"Luxembourg": {
		"en": "Luxembourg",
		"de": "Luxemburg",
		"ru": "Люксембург",
		"pt": "Luxemburgo",
		"nl": "Luxemburg",
		"fr": "Luxembourg",
		"it": "Lussemburgo",
		"es": "Luxemburgo",
		"pl": "Luksemburg",
		"zh-cn": "卢森堡"
	},
	"Ireland": {
		"en": "Ireland",
		"de": "Irland",
		"ru": "Ирландия",
		"pt": "Irlanda",
		"nl": "Ierland",
		"fr": "Irlande",
		"it": "Irlanda",
		"es": "Irlanda",
		"pl": "Irlandia",
		"zh-cn": "爱尔兰"
	},
	"Pakistan": {
		"en": "Pakistan",
		"de": "Pakistan",
		"ru": "Пакистан",
		"pt": "Paquistão",
		"nl": "Pakistan",
		"fr": "Pakistan",
		"it": "Pakistan",
		"es": "Pakistán",
		"pl": "Pakistan",
		"zh-cn": "巴基斯坦"
	},
	"Diamond Princess": {
		"en": "Diamond Princess",
		"de": "Diamantprinzessin",
		"ru": "Алмазная принцесса",
		"pt": "Diamond Princess",
		"nl": "Diamond Princess",
		"fr": "Diamond Princess",
		"it": "Diamond Princess",
		"es": "Princesa del diamante",
		"pl": "Diamentowa księżniczka",
		"zh-cn": "钻石公主"
	},
	"Chile": {
		"en": "Chile",
		"de": "Chile",
		"ru": "Чили",
		"pt": "Chile",
		"nl": "Chili",
		"fr": "Chili",
		"it": "Chile",
		"es": "Chile",
		"pl": "Chile",
		"zh-cn": "智利"
	},
	"Finland": {
		"en": "Finland",
		"de": "Finnland",
		"ru": "Финляндия",
		"pt": "Finlândia",
		"nl": "Finland",
		"fr": "Finlande",
		"it": "Finlandia",
		"es": "Finlandia",
		"pl": "Finlandia",
		"zh-cn": "芬兰"
	},
	"Thailand": {
		"en": "Thailand",
		"de": "Thailand",
		"ru": "Таиланд",
		"pt": "Tailândia",
		"nl": "Thailand",
		"fr": "Thaïlande",
		"it": "Tailandia",
		"es": "Tailandia",
		"pl": "Tajlandia",
		"zh-cn": "泰国"
	},
	"Iceland": {
		"en": "Iceland",
		"de": "Island",
		"ru": "Исландия",
		"pt": "Islândia",
		"nl": "IJsland",
		"fr": "Islande",
		"it": "Islanda",
		"es": "Islandia",
		"pl": "Islandia",
		"zh-cn": "冰岛"
	},
	"Poland": {
		"en": "Poland",
		"de": "Polen",
		"ru": "Польша",
		"pt": "Polônia",
		"nl": "Polen",
		"fr": "Pologne",
		"it": "Polonia",
		"es": "Polonia",
		"pl": "Polska",
		"zh-cn": "波兰"
	},
	"Ecuador": {
		"en": "Ecuador",
		"de": "Ecuador",
		"ru": "Эквадор",
		"pt": "Equador",
		"nl": "Ecuador",
		"fr": "Équateur",
		"it": "Ecuador",
		"es": "Ecuador",
		"pl": "Ekwador",
		"zh-cn": "厄瓜多尔"
	},
	"Greece": {
		"en": "Greece",
		"de": "Griechenland",
		"ru": "Греция",
		"pt": "Grécia",
		"nl": "Griekenland",
		"fr": "Grèce",
		"it": "Grecia",
		"es": "Grecia",
		"pl": "Grecja",
		"zh-cn": "希腊"
	},
	"Indonesia": {
		"en": "Indonesia",
		"de": "Indonesien",
		"ru": "Индонезия",
		"pt": "Indonésia",
		"nl": "Indonesië",
		"fr": "Indonésie",
		"it": "Indonesia",
		"es": "Indonesia",
		"pl": "Indonezja",
		"zh-cn": "印度尼西亚"
	},
	"Saudi Arabia": {
		"en": "Saudi Arabia",
		"de": "Saudi Arabien",
		"ru": "Саудовская Аравия",
		"pt": "Arábia Saudita",
		"nl": "Saoedi-Arabië",
		"fr": "Arabie Saoudite",
		"it": "Arabia Saudita",
		"es": "Arabia Saudita",
		"pl": "Arabia Saudyjska",
		"zh-cn": "沙特阿拉伯"
	},
	"Qatar": {
		"en": "Qatar",
		"de": "Katar",
		"ru": "Катар",
		"pt": "Catar",
		"nl": "Qatar",
		"fr": "Qatar",
		"it": "Qatar",
		"es": "Katar",
		"pl": "Katar",
		"zh-cn": "卡塔尔"
	},
	"Singapore": {
		"en": "Singapore",
		"de": "Singapur",
		"ru": "Сингапур",
		"pt": "Cingapura",
		"nl": "Singapore",
		"fr": "Singapour",
		"it": "Singapore",
		"es": "Singapur",
		"pl": "Singapur",
		"zh-cn": "新加坡"
	},
	"Romania": {
		"en": "Romania",
		"de": "Rumänien",
		"ru": "Румыния",
		"pt": "Romênia",
		"nl": "Roemenië",
		"fr": "Roumanie",
		"it": "Romania",
		"es": "Rumania",
		"pl": "Rumunia",
		"zh-cn": "罗马尼亚"
	},
	"Slovenia": {
		"en": "Slovenia",
		"de": "Slowenien",
		"ru": "Словения",
		"pt": "Eslovênia",
		"nl": "Slovenië",
		"fr": "Slovénie",
		"it": "Slovenia",
		"es": "Eslovenia",
		"pl": "Słowenia",
		"zh-cn": "斯洛文尼亚"
	},
	"India": {
		"en": "India",
		"de": "Indien",
		"ru": "Индия",
		"pt": "Índia",
		"nl": "India",
		"fr": "Inde",
		"it": "India",
		"es": "India",
		"pl": "Indie",
		"zh-cn": "印度"
	},
	"Philippines": {
		"en": "Philippines",
		"de": "Philippinen",
		"ru": "Филиппины",
		"pt": "Filipinas",
		"nl": "Filippijnen",
		"fr": "Philippines",
		"it": "Filippine",
		"es": "Filipinas",
		"pl": "Filipiny",
		"zh-cn": "菲律宾"
	},
	"Russia": {
		"en": "Russia",
		"de": "Russland",
		"ru": "Россия",
		"pt": "Rússia",
		"nl": "Rusland",
		"fr": "Russie",
		"it": "Russia",
		"es": "Rusia",
		"pl": "Rosja",
		"zh-cn": "俄国"
	},
	"Bahrain": {
		"en": "Bahrain",
		"de": "Bahrain",
		"ru": "Бахрейн",
		"pt": "Barém",
		"nl": "Bahrein",
		"fr": "Bahrein",
		"it": "Bahrain",
		"es": "Bahrein",
		"pl": "Bahrajn",
		"zh-cn": "巴林"
	},
	"Estonia": {
		"en": "Estonia",
		"de": "Estland",
		"ru": "Эстония",
		"pt": "Estônia",
		"nl": "Estland",
		"fr": "Estonie",
		"it": "Estonia",
		"es": "Estonia",
		"pl": "Estonia",
		"zh-cn": "爱沙尼亚"
	},
	"Peru": {
		"en": "Peru",
		"de": "Peru",
		"ru": "Перу",
		"pt": "Peru",
		"nl": "Peru",
		"fr": "Pérou",
		"it": "Perù",
		"es": "Perú",
		"pl": "Peru",
		"zh-cn": "秘鲁"
	},
	"Egypt": {
		"en": "Egypt",
		"de": "Ägypten",
		"ru": "Египет",
		"pt": "Egito",
		"nl": "Egypte",
		"fr": "Egypte",
		"it": "Egitto",
		"es": "Egipto",
		"pl": "Egipt",
		"zh-cn": "埃及"
	},
	"Hong Kong": {
		"en": "Hong Kong",
		"de": "Hongkong",
		"ru": "Гонконг",
		"pt": "Hong Kong",
		"nl": "Hong Kong",
		"fr": "Hong Kong",
		"it": "Hong Kong",
		"es": "Hong Kong",
		"pl": "Hongkong",
		"zh-cn": "香港"
	},
	"Mexico": {
		"en": "Mexico",
		"de": "Mexiko",
		"ru": "Мексика",
		"pt": "México",
		"nl": "Mexico",
		"fr": "Mexique",
		"it": "Messico",
		"es": "Mexico",
		"pl": "Meksyk",
		"zh-cn": "墨西哥"
	},
	"Lebanon": {
		"en": "Lebanon",
		"de": "Libanon",
		"ru": "Ливан",
		"pt": "Líbano",
		"nl": "Libanon",
		"fr": "Liban",
		"it": "Libano",
		"es": "Líbano",
		"pl": "Liban",
		"zh-cn": "黎巴嫩"
	},
	"Panama": {
		"en": "Panama",
		"de": "Panama",
		"ru": "Панама",
		"pt": "Panamá",
		"nl": "Panama",
		"fr": "Panama",
		"it": "Panama",
		"es": "Panamá",
		"pl": "Panama",
		"zh-cn": "巴拿马"
	},
	"South Africa": {
		"en": "South Africa",
		"de": "Südafrika",
		"ru": "Южная Африка",
		"pt": "África do Sul",
		"nl": "Zuid-Afrika",
		"fr": "Afrique du Sud",
		"it": "Sud Africa",
		"es": "Sudáfrica",
		"pl": "Afryka Południowa",
		"zh-cn": "南非"
	},
	"Croatia": {
		"en": "Croatia",
		"de": "Kroatien",
		"ru": "Хорватия",
		"pt": "Croácia",
		"nl": "Kroatië",
		"fr": "Croatie",
		"it": "Croazia",
		"es": "Croacia",
		"pl": "Chorwacja",
		"zh-cn": "克罗地亚"
	},
	"Iraq": {
		"en": "Iraq",
		"de": "Irak",
		"ru": "Ирак",
		"pt": "Iraque",
		"nl": "Irak",
		"fr": "Irak",
		"it": "Iraq",
		"es": "Irak",
		"pl": "Irak",
		"zh-cn": "伊拉克"
	},
	"Argentina": {
		"en": "Argentina",
		"de": "Argentinien",
		"ru": "Аргентина",
		"pt": "Argentina",
		"nl": "Argentinië",
		"fr": "Argentine",
		"it": "Argentina",
		"es": "Argentina",
		"pl": "Argentyna",
		"zh-cn": "阿根廷"
	},
	"Colombia": {
		"en": "Colombia",
		"de": "Kolumbien",
		"ru": "Колумбия",
		"pt": "Colômbia",
		"nl": "Colombia",
		"fr": "Colombie",
		"it": "Colombia",
		"es": "Colombia",
		"pl": "Kolumbia",
		"zh-cn": "哥伦比亚"
	},
	"Dominican Republic": {
		"en": "Dominican Republic",
		"de": "Dominikanische Republik",
		"ru": "Доминиканская Респблика",
		"pt": "República Dominicana",
		"nl": "Dominicaanse Republiek",
		"fr": "République Dominicaine",
		"it": "Repubblica Dominicana",
		"es": "República Dominicana",
		"pl": "Republika Dominikany",
		"zh-cn": "多明尼加共和国"
	},
	"Armenia": {
		"en": "Armenia",
		"de": "Armenien",
		"ru": "Армения",
		"pt": "Armênia",
		"nl": "Armenië",
		"fr": "Arménie",
		"it": "Armenia",
		"es": "Armenia",
		"pl": "Armenia",
		"zh-cn": "亚美尼亚"
	},
	"Serbia": {
		"en": "Serbia",
		"de": "Serbien",
		"ru": "Сербия",
		"pt": "Sérvia",
		"nl": "Servië",
		"fr": "Serbie",
		"it": "Serbia",
		"es": "Serbia",
		"pl": "Serbia",
		"zh-cn": "塞尔维亚"
	},
	"Kuwait": {
		"en": "Kuwait",
		"de": "Kuwait",
		"ru": "Кувейт",
		"pt": "Kuwait",
		"nl": "Koeweit",
		"fr": "Koweit",
		"it": "Kuwait",
		"es": "Kuwait",
		"pl": "Kuwejt",
		"zh-cn": "科威特"
	},
	"Slovakia": {
		"en": "Slovakia",
		"de": "Slowakei",
		"ru": "Словакия",
		"pt": "Eslováquia",
		"nl": "Slowakije",
		"fr": "Slovaquie",
		"it": "Slovacchia",
		"es": "Eslovaquia",
		"pl": "Słowacja",
		"zh-cn": "斯洛伐克"
	},
	"San Marino": {
		"en": "San Marino",
		"de": "San Marino",
		"ru": "Сан-Марино",
		"pt": "San Marino",
		"nl": "San Marino",
		"fr": "Saint Marin",
		"it": "San Marino",
		"es": "San Marino",
		"pl": "San Marino",
		"zh-cn": "圣马力诺"
	},
	"Bulgaria": {
		"en": "Bulgaria",
		"de": "Bulgarien",
		"ru": "Болгария",
		"pt": "Bulgária",
		"nl": "Bulgarije",
		"fr": "Bulgarie",
		"it": "Bulgaria",
		"es": "Bulgaria",
		"pl": "Bułgaria",
		"zh-cn": "保加利亚"
	},
	"Taiwan": {
		"en": "Taiwan",
		"de": "Taiwan",
		"ru": "Тайвань",
		"pt": "Taiwan",
		"nl": "Taiwan",
		"fr": "Taïwan",
		"it": "Taiwan",
		"es": "Taiwán",
		"pl": "Tajwan",
		"zh-cn": "台湾"
	},
	"UAE": {
		"en": "UAE",
		"de": "VAE",
		"ru": "ОАЭ",
		"pt": "UAE",
		"nl": "VAE",
		"fr": "Émirats arabes unis",
		"it": "Emirati Arabi Uniti",
		"es": "EAU",
		"pl": "ZEA",
		"zh-cn": "阿联酋"
	},
	"Algeria": {
		"en": "Algeria",
		"de": "Algerien",
		"ru": "Алжир",
		"pt": "Argélia",
		"nl": "Algerije",
		"fr": "Algérie",
		"it": "algeria",
		"es": "Argelia",
		"pl": "Algieria",
		"zh-cn": "阿尔及利亚"
	},
	"Latvia": {
		"en": "Latvia",
		"de": "Lettland",
		"ru": "Латвия",
		"pt": "Letônia",
		"nl": "Letland",
		"fr": "Lettonie",
		"it": "Lettonia",
		"es": "Letonia",
		"pl": "Łotwa",
		"zh-cn": "拉脱维亚"
	},
	"Uruguay": {
		"en": "Uruguay",
		"de": "Uruguay",
		"ru": "Уругвай",
		"pt": "Uruguai",
		"nl": "Uruguay",
		"fr": "Uruguay",
		"it": "Uruguay",
		"es": "Uruguay",
		"pl": "Urugwaj",
		"zh-cn": "乌拉圭"
	},
	"Hungary": {
		"en": "Hungary",
		"de": "Ungarn",
		"ru": "Венгрия",
		"pt": "Hungria",
		"nl": "Hongarije",
		"fr": "Hongrie",
		"it": "Ungheria",
		"es": "Hungría",
		"pl": "Węgry",
		"zh-cn": "匈牙利"
	},
	"Lithuania": {
		"en": "Lithuania",
		"de": "Litauen",
		"ru": "Литва",
		"pt": "Lituânia",
		"nl": "Litouwen",
		"fr": "Lituanie",
		"it": "Lituania",
		"es": "Lituania",
		"pl": "Litwa",
		"zh-cn": "立陶宛"
	},
	"Costa Rica": {
		"en": "Costa Rica",
		"de": "Costa Rica",
		"ru": "Коста Рика",
		"pt": "Costa Rica",
		"nl": "Costa Rica",
		"fr": "Costa Rica",
		"it": "Costa Rica",
		"es": "Costa Rica",
		"pl": "Kostaryka",
		"zh-cn": "哥斯达黎加"
	},
	"North Macedonia": {
		"en": "North Macedonia",
		"de": "Nordmakedonien",
		"ru": "Северная Македония",
		"pt": "Macedônia do Norte",
		"nl": "Noord-Macedonië",
		"fr": "Macédoine du Nord",
		"it": "Macedonia del Nord",
		"es": "Macedonia del norte",
		"pl": "Macedonia Północna",
		"zh-cn": "北马其顿"
	},
	"Faeroe Islands": {
		"en": "Faeroe Islands",
		"de": "Färöer",
		"ru": "Фарерские острова",
		"pt": "Ilhas Faroé",
		"nl": "Faeröer",
		"fr": "Îles Féroé",
		"it": "Isole Fær Øer",
		"es": "Islas Feroe",
		"pl": "Wyspy Owcze",
		"zh-cn": "法罗群岛"
	},
	"Andorra": {
		"en": "Andorra",
		"de": "Andorra",
		"ru": "андорра",
		"pt": "Andorra",
		"nl": "Andorra",
		"fr": "Andorre",
		"it": "Andorra",
		"es": "Andorra",
		"pl": "Andora",
		"zh-cn": "安道尔"
	},
	"Morocco": {
		"en": "Morocco",
		"de": "Marokko",
		"ru": "Марокко",
		"pt": "Marrocos",
		"nl": "Marokko",
		"fr": "Maroc",
		"it": "Marocco",
		"es": "Marruecos",
		"pl": "Maroko",
		"zh-cn": "摩洛哥"
	},
	"Vietnam": {
		"en": "Vietnam",
		"de": "Vietnam",
		"ru": "Вьетнам",
		"pt": "Vietnã",
		"nl": "Vietnam",
		"fr": "Vietnam",
		"it": "Vietnam",
		"es": "Vietnam",
		"pl": "Wietnam",
		"zh-cn": "越南"
	},
	"Jordan": {
		"en": "Jordan",
		"de": "Jordan",
		"ru": "Иордания",
		"pt": "Jordânia",
		"nl": "Jordanië",
		"fr": "Jordan",
		"it": "Giordania",
		"es": "Jordán",
		"pl": "Jordania",
		"zh-cn": "约旦"
	},
	"Bosnia and Herzegovina": {
		"en": "Bosnia and Herzegovina",
		"de": "Bosnien und Herzegowina",
		"ru": "Босния и Герцеговина",
		"pt": "Bósnia e Herzegovina",
		"nl": "Bosnië-Herzegovina",
		"fr": "Bosnie Herzégovine",
		"it": "Bosnia Erzegovina",
		"es": "Bosnia y Herzegovina",
		"pl": "Bośnia i Hercegowina",
		"zh-cn": "波斯尼亚和黑塞哥维那"
	},
	"Malta": {
		"en": "Malta",
		"de": "Malta",
		"ru": "Мальта",
		"pt": "Malta",
		"nl": "Malta",
		"fr": "Malte",
		"it": "Malta",
		"es": "Malta",
		"pl": "Malta",
		"zh-cn": "马耳他"
	},
	"Albania": {
		"en": "Albania",
		"de": "Albanien",
		"ru": "Албания",
		"pt": "Albânia",
		"nl": "Albanië",
		"fr": "Albanie",
		"it": "Albania",
		"es": "Albania",
		"pl": "Albania",
		"zh-cn": "阿尔巴尼亚"
	},
	"Cyprus": {
		"en": "Cyprus",
		"de": "Zypern",
		"ru": "Кипр",
		"pt": "Chipre",
		"nl": "Cyprus",
		"fr": "Chypre",
		"it": "Cipro",
		"es": "Chipre",
		"pl": "Cypr",
		"zh-cn": "塞浦路斯"
	},
	"Brunei": {
		"en": "Brunei",
		"de": "Brunei",
		"ru": "Бруней",
		"pt": "Brunei",
		"nl": "Brunei",
		"fr": "Brunei",
		"it": "Brunei",
		"es": "Brunei",
		"pl": "Brunei",
		"zh-cn": "文莱"
	},
	"Sri Lanka": {
		"en": "Sri Lanka",
		"de": "Sri Lanka",
		"ru": "Шри-Ланка",
		"pt": "Sri Lanka",
		"nl": "Sri Lanka",
		"fr": "Sri Lanka",
		"it": "Sri Lanka",
		"es": "Sri Lanka",
		"pl": "Sri Lanka",
		"zh-cn": "斯里兰卡"
	},
	"Moldova": {
		"en": "Moldova",
		"de": "Moldawien",
		"ru": "Молдова",
		"pt": "Moldova",
		"nl": "Moldavië",
		"fr": "Moldova",
		"it": "Moldova",
		"es": "Moldavia",
		"pl": "Moldova",
		"zh-cn": "摩尔多瓦"
	},
	"Belarus": {
		"en": "Belarus",
		"de": "Weißrussland",
		"ru": "Беларусь",
		"pt": "Bielorrússia",
		"nl": "Wit-Rusland",
		"fr": "Biélorussie",
		"it": "Bielorussia",
		"es": "Bielorrusia",
		"pl": "Białoruś",
		"zh-cn": "白俄罗斯"
	},
	"Burkina Faso": {
		"en": "Burkina Faso",
		"de": "Burkina Faso",
		"ru": "Буркина-Фасо",
		"pt": "Burkina Faso",
		"nl": "Burkina Faso",
		"fr": "Burkina Faso",
		"it": "Burkina Faso",
		"es": "Burkina Faso",
		"pl": "Burkina Faso",
		"zh-cn": "布基纳法索"
	},
	"Tunisia": {
		"en": "Tunisia",
		"de": "Tunesien",
		"ru": "Тунис",
		"pt": "Tunísia",
		"nl": "Tunesië",
		"fr": "Tunisie",
		"it": "Tunisia",
		"es": "Túnez",
		"pl": "Tunezja",
		"zh-cn": "突尼斯"
	},
	"Venezuela": {
		"en": "Venezuela",
		"de": "Venezuela",
		"ru": "Венесуэла",
		"pt": "Venezuela",
		"nl": "Venezuela",
		"fr": "Venezuela",
		"it": "Venezuela",
		"es": "Venezuela",
		"pl": "Wenezuela",
		"zh-cn": "委内瑞拉"
	},
	"New Zealand": {
		"en": "New Zealand",
		"de": "Neuseeland",
		"ru": "Новая Зеландия",
		"pt": "Nova Zelândia",
		"nl": "Nieuw-Zeeland",
		"fr": "Nouvelle-Zélande",
		"it": "Nuova Zelanda",
		"es": "Nueva Zelanda",
		"pl": "Nowa Zelandia",
		"zh-cn": "新西兰"
	},
	"Azerbaijan": {
		"en": "Azerbaijan",
		"de": "Aserbaidschan",
		"ru": "Азербайджан",
		"pt": "Azerbaijão",
		"nl": "Azerbeidzjan",
		"fr": "Azerbaïdjan",
		"it": "Azerbaijan",
		"es": "Azerbaiyán",
		"pl": "Azerbejdżan",
		"zh-cn": "阿塞拜疆"
	},
	"Palestine": {
		"en": "Palestine",
		"de": "Palästina",
		"ru": "Палестина",
		"pt": "Palestina",
		"nl": "Palestina",
		"fr": "Palestine",
		"it": "Palestina",
		"es": "Palestina",
		"pl": "Palestyna",
		"zh-cn": "巴勒斯坦"
	},
	"Kazakhstan": {
		"en": "Kazakhstan",
		"de": "Kasachstan",
		"ru": "Казахстан",
		"pt": "Cazaquistão",
		"nl": "Kazachstan",
		"fr": "Kazakhstan",
		"it": "Kazakistan",
		"es": "Kazajstán",
		"pl": "Kazachstan",
		"zh-cn": "哈萨克斯坦"
	},
	"Guadeloupe": {
		"en": "Guadeloupe",
		"de": "Guadeloupe",
		"ru": "Гваделупа",
		"pt": "Guadalupe",
		"nl": "Guadeloupe",
		"fr": "Guadeloupe",
		"it": "Guadeloupe",
		"es": "Guadalupe",
		"pl": "Gwadelupa",
		"zh-cn": "瓜德罗普岛"
	},
	"Senegal": {
		"en": "Senegal",
		"de": "Senegal",
		"ru": "Сенегал",
		"pt": "Senegal",
		"nl": "Senegal",
		"fr": "Sénégal",
		"it": "Senegal",
		"es": "Senegal",
		"pl": "Senegal",
		"zh-cn": "塞内加尔"
	},
	"Oman": {
		"en": "Oman",
		"de": "Oman",
		"ru": "Оман",
		"pt": "Omã",
		"nl": "Oman",
		"fr": "Oman",
		"it": "Oman",
		"es": "Omán",
		"pl": "Oman",
		"zh-cn": "阿曼"
	},
	"Georgia": {
		"en": "Georgia",
		"de": "Georgia",
		"ru": "Грузия",
		"pt": "Geórgia",
		"nl": "Georgië",
		"fr": "Géorgie",
		"it": "Georgia",
		"es": "Georgia",
		"pl": "Gruzja",
		"zh-cn": "佐治亚州"
	},
	"Cambodia": {
		"en": "Cambodia",
		"de": "Kambodscha",
		"ru": "Камбоджа",
		"pt": "Camboja",
		"nl": "Cambodja",
		"fr": "Cambodge",
		"it": "Cambogia",
		"es": "Camboya",
		"pl": "Kambodża",
		"zh-cn": "柬埔寨"
	},
	"Trinidad and Tobago": {
		"en": "Trinidad and Tobago",
		"de": "Trinidad und Tobago",
		"ru": "Тринидад и Тобаго",
		"pt": "Trindade e Tobago",
		"nl": "Trinidad en Tobago",
		"fr": "Trinité-et-Tobago",
		"it": "Trinidad e Tobago",
		"es": "Trinidad y Tobago",
		"pl": "Trynidad i Tobago",
		"zh-cn": "特立尼达和多巴哥"
	},
	"Ukraine": {
		"en": "Ukraine",
		"de": "Ukraine",
		"ru": "Украина",
		"pt": "Ucrânia",
		"nl": "Oekraïne",
		"fr": "Ukraine",
		"it": "Ucraina",
		"es": "Ucrania",
		"pl": "Ukraina",
		"zh-cn": "乌克兰"
	},
	"Réunion": {
		"en": "Réunion",
		"de": "Wiedervereinigung",
		"ru": "Реюньон",
		"pt": "Reunião",
		"nl": "Bijeenkomst",
		"fr": "Réunion",
		"it": "Riunione",
		"es": "Reunión",
		"pl": "Zjazd",
		"zh-cn": "团圆"
	},
	"Uzbekistan": {
		"en": "Uzbekistan",
		"de": "Usbekistan",
		"ru": "Узбекистан",
		"pt": "Usbequistão",
		"nl": "Oezbekistan",
		"fr": "Ouzbékistan",
		"it": "Uzbekistan",
		"es": "Uzbekistán",
		"pl": "Uzbekistan",
		"zh-cn": "乌兹别克斯坦"
	},
	"Cameroon": {
		"en": "Cameroon",
		"de": "Kamerun",
		"ru": "Камерун",
		"pt": "Camarões",
		"nl": "Kameroen",
		"fr": "Cameroun",
		"it": "Camerun",
		"es": "Camerún",
		"pl": "Kamerun",
		"zh-cn": "喀麦隆"
	},
	"Martinique": {
		"en": "Martinique",
		"de": "Martinique",
		"ru": "Мартиника",
		"pt": "Martinica",
		"nl": "Martinique",
		"fr": "Martinique",
		"it": "Martinique",
		"es": "Martinica",
		"pl": "Martynika",
		"zh-cn": "马提尼克岛"
	},
	"Liechtenstein": {
		"en": "Liechtenstein",
		"de": "Liechtenstein",
		"ru": "Лихтенштейн",
		"pt": "Liechtenstein",
		"nl": "Liechtenstein",
		"fr": "Liechtenstein",
		"it": "Liechtenstein",
		"es": "Liechtenstein",
		"pl": "Liechtenstein",
		"zh-cn": "列支敦士登"
	},
	"Afghanistan": {
		"en": "Afghanistan",
		"de": "Afghanistan",
		"ru": "Афганистан",
		"pt": "Afeganistão",
		"nl": "Afghanistan",
		"fr": "Afghanistan",
		"it": "afghanistan",
		"es": "Afganistán",
		"pl": "Afganistan",
		"zh-cn": "阿富汗"
	},
	"Channel Islands": {
		"en": "Channel Islands",
		"de": "Kanalinseln",
		"ru": "Нормандские острова",
		"pt": "Ilhas do Canal",
		"nl": "Kanaal eilanden",
		"fr": "Îles anglo-normandes",
		"it": "Isole del Canale",
		"es": "Islas del Canal",
		"pl": "Wyspy Normandzkie",
		"zh-cn": "海峡群岛"
	},
	"Bangladesh": {
		"en": "Bangladesh",
		"de": "Bangladesch",
		"ru": "Бангладеш",
		"pt": "Bangladesh",
		"nl": "Bangladesh",
		"fr": "Bangladesh",
		"it": "Bangladesh",
		"es": "Bangladesh",
		"pl": "Bangladesz",
		"zh-cn": "孟加拉国"
	},
	"Guam": {
		"en": "Guam",
		"de": "Guam",
		"ru": "Гуам",
		"pt": "Guam",
		"nl": "Guam",
		"fr": "Guam",
		"it": "Guam",
		"es": "Guam",
		"pl": "Guam",
		"zh-cn": "关岛"
	},
	"Nigeria": {
		"en": "Nigeria",
		"de": "Nigeria",
		"ru": "Нигерия",
		"pt": "Nigéria",
		"nl": "Nigeria",
		"fr": "Nigeria",
		"it": "Nigeria",
		"es": "Nigeria",
		"pl": "Nigeria",
		"zh-cn": "奈及利亚"
	},
	"Honduras": {
		"en": "Honduras",
		"de": "Honduras",
		"ru": "Гондурас",
		"pt": "Honduras",
		"nl": "Honduras",
		"fr": "Honduras",
		"it": "Honduras",
		"es": "Honduras",
		"pl": "Honduras",
		"zh-cn": "洪都拉斯"
	},
	"Bolivia": {
		"en": "Bolivia",
		"de": "Bolivien",
		"ru": "Боливия",
		"pt": "Bolívia",
		"nl": "Bolivia",
		"fr": "Bolivie",
		"it": "Bolivia",
		"es": "Bolivia",
		"pl": "Boliwia",
		"zh-cn": "玻利维亚"
	},
	"DRC": {
		"en": "DRC",
		"de": "DRC",
		"ru": "DRC",
		"pt": "RDC",
		"nl": "DRC",
		"fr": "RDC",
		"it": "RDC",
		"es": "DRC",
		"pl": "DRK",
		"zh-cn": "刚果民主共和国"
	},
	"Puerto Rico": {
		"en": "Puerto Rico",
		"de": "Puerto Rico",
		"ru": "Пуэрто-Рико",
		"pt": "Porto Rico",
		"nl": "Puerto Rico",
		"fr": "Porto Rico",
		"it": "Puerto Rico",
		"es": "Puerto Rico",
		"pl": "Portoryko",
		"zh-cn": "波多黎各"
	},
	"Paraguay": {
		"en": "Paraguay",
		"de": "Paraguay",
		"ru": "Парагвай",
		"pt": "Paraguai",
		"nl": "Paraguay",
		"fr": "Paraguay",
		"it": "Paraguay",
		"es": "Paraguay",
		"pl": "Paragwaj",
		"zh-cn": "巴拉圭"
	},
	"Cuba": {
		"en": "Cuba",
		"de": "Kuba",
		"ru": "Куба",
		"pt": "Cuba",
		"nl": "Cuba",
		"fr": "Cuba",
		"it": "Cuba",
		"es": "Cuba",
		"pl": "Kuba",
		"zh-cn": "古巴"
	},
	"Ghana": {
		"en": "Ghana",
		"de": "Ghana",
		"ru": "Гана",
		"pt": "Gana",
		"nl": "Ghana",
		"fr": "Ghana",
		"it": "Ghana",
		"es": "Ghana",
		"pl": "Ghana",
		"zh-cn": "加纳"
	},
	"Macao": {
		"en": "Macao",
		"de": "Macao",
		"ru": "Macao",
		"pt": "Macau",
		"nl": "Macao",
		"fr": "Macao",
		"it": "Macao",
		"es": "Macao",
		"pl": "Makao",
		"zh-cn": "澳门"
	},
	"Jamaica": {
		"en": "Jamaica",
		"de": "Jamaika",
		"ru": "Ямайка",
		"pt": "Jamaica",
		"nl": "Jamaica",
		"fr": "Jamaïque",
		"it": "Giamaica",
		"es": "Jamaica",
		"pl": "Jamajka",
		"zh-cn": "牙买加"
	},
	"Guyana": {
		"en": "Guyana",
		"de": "Guyana",
		"ru": "Гайана",
		"pt": "Guiana",
		"nl": "Guyana",
		"fr": "Guyane",
		"it": "Guyana",
		"es": "Guayana",
		"pl": "Gujana",
		"zh-cn": "圭亚那"
	},
	"Mauritius": {
		"en": "Mauritius",
		"de": "Mauritius",
		"ru": "Маврикий",
		"pt": "Maurícia",
		"nl": "Mauritius",
		"fr": "Maurice",
		"it": "Mauritius",
		"es": "Mauricio",
		"pl": "Mauritius",
		"zh-cn": "毛里求斯"
	},
	"Monaco": {
		"en": "Monaco",
		"de": "Monaco",
		"ru": "Монако",
		"pt": "Mônaco",
		"nl": "Monaco",
		"fr": "Monaco",
		"it": "Monaco",
		"es": "Mónaco",
		"pl": "Monako",
		"zh-cn": "摩纳哥"
	},
	"French Guiana": {
		"en": "French Guiana",
		"de": "Französisch-Guayana",
		"ru": "Французская Гвиана",
		"pt": "Guiana Francesa",
		"nl": "Frans-Guyana",
		"fr": "Guyane Française",
		"it": "Guiana francese",
		"es": "Guayana Francesa",
		"pl": "Gujana Francuska",
		"zh-cn": "法属圭亚那"
	},
	"Guatemala": {
		"en": "Guatemala",
		"de": "Guatemala",
		"ru": "Гватемала",
		"pt": "Guatemala",
		"nl": "Guatemala",
		"fr": "Guatemala",
		"it": "Guatemala",
		"es": "Guatemala",
		"pl": "Gwatemala",
		"zh-cn": "危地马拉"
	},
	"Rwanda": {
		"en": "Rwanda",
		"de": "Ruanda",
		"ru": "Руанда",
		"pt": "Ruanda",
		"nl": "Rwanda",
		"fr": "Rwanda",
		"it": "Ruanda",
		"es": "Ruanda",
		"pl": "Rwanda",
		"zh-cn": "卢旺达"
	},
	"Montenegro": {
		"en": "Montenegro",
		"de": "Montenegro",
		"ru": "Черногория",
		"pt": "Montenegro",
		"nl": "Montenegro",
		"fr": "Monténégro",
		"it": "Montenegro",
		"es": "Montenegro",
		"pl": "Czarnogóra",
		"zh-cn": "黑山共和国"
	},
	"Togo": {
		"en": "Togo",
		"de": "Gehen",
		"ru": "Идти",
		"pt": "Ir",
		"nl": "Gaan",
		"fr": "Aller",
		"it": "Andare",
		"es": "Ir",
		"pl": "Iść",
		"zh-cn": "多哥"
	},
	"French Polynesia": {
		"en": "French Polynesia",
		"de": "Französisch Polynesien",
		"ru": "Французская Полинезия",
		"pt": "Polinésia Francesa",
		"nl": "Frans-Polynesië",
		"fr": "Polynésie française",
		"it": "Polinesia francese",
		"es": "Polinesia francés",
		"pl": "Polinezja Francuska",
		"zh-cn": "法属波利尼西亚"
	},
	"Barbados": {
		"en": "Barbados",
		"de": "Barbados",
		"ru": "Барбадос",
		"pt": "Barbados",
		"nl": "Barbados",
		"fr": "Barbade",
		"it": "Barbados",
		"es": "Barbados",
		"pl": "Barbados",
		"zh-cn": "巴巴多斯"
	},
	"Ivory Coast": {
		"en": "Ivory Coast",
		"de": "Elfenbeinküste",
		"ru": "Кот-д'Ивуар",
		"pt": "Costa do Marfim",
		"nl": "Ivoorkust",
		"fr": "Côte d'Ivoire",
		"it": "Costa d'Avorio",
		"es": "Costa de Marfil",
		"pl": "Wybrzeże Kości Słoniowej",
		"zh-cn": "象牙海岸"
	},
	"Kyrgyzstan": {
		"en": "Kyrgyzstan",
		"de": "Kirgisistan",
		"ru": "Киргизия",
		"pt": "Quirguistão",
		"nl": "Kirgizië",
		"fr": "Kirghizistan",
		"it": "Kyrgyzstan",
		"es": "Kirguistán",
		"pl": "Kirgistan",
		"zh-cn": "吉尔吉斯斯坦"
	},
	"Maldives": {
		"en": "Maldives",
		"de": "Malediven",
		"ru": "Мальдивы",
		"pt": "Maldivas",
		"nl": "Maldiven",
		"fr": "Maldives",
		"it": "Maldive",
		"es": "Maldivas",
		"pl": "Malediwy",
		"zh-cn": "马尔代夫"
	},
	"Tanzania": {
		"en": "Tanzania",
		"de": "Tansania",
		"ru": "Танзания",
		"pt": "Tanzânia",
		"nl": "Tanzania",
		"fr": "Tanzanie",
		"it": "Tanzania",
		"es": "Tanzania",
		"pl": "Tanzania",
		"zh-cn": "坦桑尼亚"
	},
	"Ethiopia": {
		"en": "Ethiopia",
		"de": "Äthiopien",
		"ru": "Эфиопия",
		"pt": "Etiópia",
		"nl": "Ethiopië",
		"fr": "Ethiopie",
		"it": "Etiopia",
		"es": "Etiopía",
		"pl": "Etiopia",
		"zh-cn": "埃塞俄比亚"
	},
	"Mayotte": {
		"en": "Mayotte",
		"de": "Mayotte",
		"ru": "Майотта",
		"pt": "Mayotte",
		"nl": "Mayotte",
		"fr": "Mayotte",
		"it": "Mayotte",
		"es": "Mayotte",
		"pl": "Majotta",
		"zh-cn": "马约特岛"
	},
	"Gibraltar": {
		"en": "Gibraltar",
		"de": "Gibraltar",
		"ru": "Гибралтар",
		"pt": "Gibraltar",
		"nl": "Gibraltar",
		"fr": "Gibraltar",
		"it": "Gibilterra",
		"es": "Gibraltar",
		"pl": "Gibraltar",
		"zh-cn": "直布罗陀"
	},
	"Mongolia": {
		"en": "Mongolia",
		"de": "Mongolei",
		"ru": "Монголия",
		"pt": "Mongólia",
		"nl": "Mongolië",
		"fr": "Mongolie",
		"it": "Mongolia",
		"es": "Mongolia",
		"pl": "Mongolia",
		"zh-cn": "蒙古"
	},
	"Aruba": {
		"en": "Aruba",
		"de": "Aruba",
		"ru": "Аруба",
		"pt": "Aruba",
		"nl": "Aruba",
		"fr": "Aruba",
		"it": "aruba",
		"es": "Aruba",
		"pl": "Aruba",
		"zh-cn": "阿鲁巴岛"
	},
	"Kenya": {
		"en": "Kenya",
		"de": "Kenia",
		"ru": "Кения",
		"pt": "Quênia",
		"nl": "Kenia",
		"fr": "Kenya",
		"it": "Kenia",
		"es": "Kenia",
		"pl": "Kenia",
		"zh-cn": "肯尼亚"
	},
	"Seychelles": {
		"en": "Seychelles",
		"de": "Seychellen",
		"ru": "Сейшельские острова",
		"pt": "Seychelles",
		"nl": "Seychellen",
		"fr": "les Seychelles",
		"it": "Seychelles",
		"es": "Seychelles",
		"pl": "Seszele",
		"zh-cn": "塞舌尔"
	},
	"Equatorial Guinea": {
		"en": "Equatorial Guinea",
		"de": "Äquatorialguinea",
		"ru": "Экваториальная Гвинея",
		"pt": "Guiné Equatorial",
		"nl": "Equatoriaal-Guinea",
		"fr": "Guinée Équatoriale",
		"it": "Guinea Equatoriale",
		"es": "Guinea Ecuatorial",
		"pl": "Gwinea Równikowa",
		"zh-cn": "赤道几内亚"
	},
	"U.S. Virgin Islands": {
		"en": "U.S. Virgin Islands",
		"de": "US Jungferninseln",
		"ru": "Виргинские острова США",
		"pt": "Ilhas Virgens Americanas",
		"nl": "Amerikaanse Maagdeneilanden",
		"fr": "Îles Vierges américaines",
		"it": "Isole Vergini americane",
		"es": "Islas Vírgenes de EE.UU",
		"pl": "Wyspy Dziewicze Stanów Zjednoczonych",
		"zh-cn": "美属维尔京群岛"
	},
	"Gabon": {
		"en": "Gabon",
		"de": "Gabun",
		"ru": "Габон",
		"pt": "Gabão",
		"nl": "Gabon",
		"fr": "Gabon",
		"it": "Gabon",
		"es": "Gabón",
		"pl": "Gabon",
		"zh-cn": "加蓬"
	},
	"Isle of Man": {
		"en": "Isle of Man",
		"de": "Isle of Man",
		"ru": "Остров Мэн",
		"pt": "Ilha de Man",
		"nl": "Isle of Man",
		"fr": "île de Man",
		"it": "Isola di Man",
		"es": "Isla del hombre",
		"pl": "Wyspa Man",
		"zh-cn": "马恩岛"
	},
	"Saint Martin": {
		"en": "Saint Martin",
		"de": "Sankt Martin",
		"ru": "Святой мартин",
		"pt": "são Martinho",
		"nl": "Sint-Maarten",
		"fr": "Saint Martin",
		"it": "Saint Martin",
		"es": "San Martín",
		"pl": "święty Marcin",
		"zh-cn": "圣马丁"
	},
	"Suriname": {
		"en": "Suriname",
		"de": "Suriname",
		"ru": "Суринам",
		"pt": "Suriname",
		"nl": "Suriname",
		"fr": "Suriname",
		"it": "Suriname",
		"es": "Surinam",
		"pl": "Surinam",
		"zh-cn": "苏里南"
	},
	"Bahamas": {
		"en": "Bahamas",
		"de": "Bahamas",
		"ru": "Багамские о-ва",
		"pt": "Bahamas",
		"nl": "Bahamas",
		"fr": "Bahamas",
		"it": "Bahamas",
		"es": "Bahamas",
		"pl": "Bahamy",
		"zh-cn": "巴哈马"
	},
	"New Caledonia": {
		"en": "New Caledonia",
		"de": "Neu-Kaledonien",
		"ru": "Новая Каледония",
		"pt": "Nova Caledônia",
		"nl": "Nieuw-Caledonië",
		"fr": "Nouvelle Calédonie",
		"it": "Nuova Caledonia",
		"es": "Nueva Caledonia",
		"pl": "Nowa Kaledonia",
		"zh-cn": "新喀里多尼亚"
	},
	"Eswatini": {
		"en": "Eswatini",
		"de": "Eswatini",
		"ru": "Eswatini",
		"pt": "Eswatini",
		"nl": "Eswatini",
		"fr": "Eswatini",
		"it": "Eswatini",
		"es": "Eswatini",
		"pl": "Eswatini",
		"zh-cn": "埃斯瓦蒂尼"
	},
	"Cayman Islands": {
		"en": "Cayman Islands",
		"de": "Cayman Inseln",
		"ru": "Каймановы острова",
		"pt": "Ilhas Cayman",
		"nl": "Kaaiman Eilanden",
		"fr": "Îles Caïmans",
		"it": "Isole Cayman",
		"es": "Islas Caimán",
		"pl": "Kajmany",
		"zh-cn": "开曼群岛"
	},
	"Curaçao": {
		"en": "Curaçao",
		"de": "Curacao",
		"ru": "Кюрасао",
		"pt": "Curaçao",
		"nl": "Curacao",
		"fr": "Curacao",
		"it": "Curacao",
		"es": "Curazao",
		"pl": "Curaçao",
		"zh-cn": "库拉索"
	},
	"Cabo Verde": {
		"en": "Cabo Verde",
		"de": "Cabo Verde",
		"ru": "Кабо Верде",
		"pt": "Cabo Verde",
		"nl": "Cabo Verde",
		"fr": "Cabo Verde",
		"it": "Cabo Verde",
		"es": "Cabo Verde",
		"pl": "Cabo Verde",
		"zh-cn": "佛得角"
	},
	"CAR": {
		"en": "CAR",
		"de": "AUTO",
		"ru": "МАШИНА",
		"pt": "CARRO",
		"nl": "AUTO",
		"fr": "VOITURE",
		"it": "AUTO",
		"es": "COCHE",
		"pl": "SAMOCHÓD",
		"zh-cn": "汽车"
	},
	"Congo": {
		"en": "Congo",
		"de": "Kongo",
		"ru": "Конго",
		"pt": "Congo",
		"nl": "Congo",
		"fr": "Congo",
		"it": "Congo",
		"es": "Congo",
		"pl": "Kongo",
		"zh-cn": "刚果"
	},
	"El Salvador": {
		"en": "El Salvador",
		"de": "El Salvador",
		"ru": "Сальвадор",
		"pt": "El Salvador",
		"nl": "El Salvador",
		"fr": "Le Salvador",
		"it": "El Salvador",
		"es": "El Salvador",
		"pl": "Salwador",
		"zh-cn": "萨尔瓦多"
	},
	"Liberia": {
		"en": "Liberia",
		"de": "Liberia",
		"ru": "Либерия",
		"pt": "Libéria",
		"nl": "Liberia",
		"fr": "Libéria",
		"it": "Liberia",
		"es": "Liberia",
		"pl": "Liberia",
		"zh-cn": "利比里亚"
	},
	"Madagascar": {
		"en": "Madagascar",
		"de": "Madagaskar",
		"ru": "Мадагаскар",
		"pt": "Madagáscar",
		"nl": "Madagascar",
		"fr": "Madagascar",
		"it": "Madagascar",
		"es": "Madagascar",
		"pl": "Madagaskar",
		"zh-cn": "马达加斯加"
	},
	"Namibia": {
		"en": "Namibia",
		"de": "Namibia",
		"ru": "Намибия",
		"pt": "Namíbia",
		"nl": "Namibië",
		"fr": "Namibie",
		"it": "Namibia",
		"es": "Namibia",
		"pl": "Namibia",
		"zh-cn": "纳米比亚"
	},
	"St. Barth": {
		"en": "St. Barth",
		"de": "St. Barth",
		"ru": "Сен-Барт",
		"pt": "St. Barth",
		"nl": "St. Barth",
		"fr": "Saint-Barth",
		"it": "St. Barth",
		"es": "St. Barth",
		"pl": "St. Barth",
		"zh-cn": "圣巴特"
	},
	"Zambia": {
		"en": "Zambia",
		"de": "Sambia",
		"ru": "Замбия",
		"pt": "Zâmbia",
		"nl": "Zambia",
		"fr": "Zambie",
		"it": "Zambia",
		"es": "Zambia",
		"pl": "Zambia",
		"zh-cn": "赞比亚"
	},
	"Zimbabwe": {
		"en": "Zimbabwe",
		"de": "Zimbabwe",
		"ru": "Зимбабве",
		"pt": "Zimbábue",
		"nl": "Zimbabwe",
		"fr": "Zimbabwe",
		"it": "Zimbabwe",
		"es": "Zimbabue",
		"pl": "Zimbabwe",
		"zh-cn": "津巴布韦"
	},
	"Sudan": {
		"en": "Sudan",
		"de": "Sudan",
		"ru": "Судан",
		"pt": "Sudão",
		"nl": "Soedan",
		"fr": "Soudan",
		"it": "Sudan",
		"es": "Sudán",
		"pl": "Sudan",
		"zh-cn": "苏丹"
	},
	"Nepal": {
		"en": "Nepal",
		"de": "Nepal",
		"ru": "Непал",
		"pt": "Nepal",
		"nl": "Nepal",
		"fr": "Népal",
		"it": "Nepal",
		"es": "Nepal",
		"pl": "Nepal",
		"zh-cn": "尼泊尔"
	},
	"Angola": {
		"en": "Angola",
		"de": "Angola",
		"ru": "Ангола",
		"pt": "Angola",
		"nl": "Angola",
		"fr": "Angola",
		"it": "angola",
		"es": "Angola",
		"pl": "Angola",
		"zh-cn": "安哥拉"
	},
	"Benin": {
		"en": "Benin",
		"de": "Benin",
		"ru": "Бенин",
		"pt": "Benin",
		"nl": "Benin",
		"fr": "Bénin",
		"it": "Benin",
		"es": "Benin",
		"pl": "Benin",
		"zh-cn": "贝宁"
	},
	"Bermuda": {
		"en": "Bermuda",
		"de": "Bermuda",
		"ru": "Бермудские острова",
		"pt": "Bermudas",
		"nl": "Bermuda",
		"fr": "Bermudes",
		"it": "Bermuda",
		"es": "islas Bermudas",
		"pl": "Bermudy",
		"zh-cn": "百慕大"
	},
	"Bhutan": {
		"en": "Bhutan",
		"de": "Bhutan",
		"ru": "Бутан",
		"pt": "Butão",
		"nl": "Bhutan",
		"fr": "Bhoutan",
		"it": "Bhutan",
		"es": "Bután",
		"pl": "Bhutan",
		"zh-cn": "不丹"
	},
	"Fiji": {
		"en": "Fiji",
		"de": "Fidschi",
		"ru": "Фиджи",
		"pt": "Fiji",
		"nl": "Fiji",
		"fr": "Fidji",
		"it": "Fiji",
		"es": "Fiyi",
		"pl": "Fidżi",
		"zh-cn": "斐济"
	},
	"Greenland": {
		"en": "Greenland",
		"de": "Grönland",
		"ru": "Гренландия",
		"pt": "Gronelândia",
		"nl": "Groenland",
		"fr": "Groenland",
		"it": "Groenlandia",
		"es": "Groenlandia",
		"pl": "Grenlandia",
		"zh-cn": "格陵兰"
	},
	"Guinea": {
		"en": "Guinea",
		"de": "Guinea",
		"ru": "Гвинея",
		"pt": "Guiné",
		"nl": "Guinea",
		"fr": "Guinée",
		"it": "Guinea",
		"es": "Guinea",
		"pl": "Gwinea",
		"zh-cn": "几内亚"
	},
	"Haiti": {
		"en": "Haiti",
		"de": "Haiti",
		"ru": "Гаити",
		"pt": "Haiti",
		"nl": "Haïti",
		"fr": "Haïti",
		"it": "Haiti",
		"es": "Haití",
		"pl": "Haiti",
		"zh-cn": "海地"
	},
	"Mauritania": {
		"en": "Mauritania",
		"de": "Mauretanien",
		"ru": "Мавритания",
		"pt": "Mauritânia",
		"nl": "Mauritanië",
		"fr": "Mauritanie",
		"it": "Mauritania",
		"es": "Mauritania",
		"pl": "Mauretania",
		"zh-cn": "毛里塔尼亚"
	},
	"Nicaragua": {
		"en": "Nicaragua",
		"de": "Nicaragua",
		"ru": "Никарагуа",
		"pt": "Nicarágua",
		"nl": "Nicaragua",
		"fr": "Nicaragua",
		"it": "Nicaragua",
		"es": "Nicaragua",
		"pl": "Nikaragua",
		"zh-cn": "尼加拉瓜"
	},
	"Niger": {
		"en": "Niger",
		"de": "Niger",
		"ru": "Нигер",
		"pt": "Níger",
		"nl": "Niger",
		"fr": "Niger",
		"it": "Niger",
		"es": "Níger",
		"pl": "Niger",
		"zh-cn": "尼日尔"
	},
	"Saint Lucia": {
		"en": "Saint Lucia",
		"de": "St. Lucia",
		"ru": "Сент-Люсия",
		"pt": "Santa Lúcia",
		"nl": "Saint Lucia",
		"fr": "Sainte-Lucie",
		"it": "Santa Lucia",
		"es": "Santa Lucía",
		"pl": "święta Lucia",
		"zh-cn": "圣卢西亚"
	},
	"Antigua and Barbuda": {
		"en": "Antigua and Barbuda",
		"de": "Antigua und Barbuda",
		"ru": "Антигуа и Барбуда",
		"pt": "Antígua e Barbuda",
		"nl": "Antigua en Barbuda",
		"fr": "Antigua-et-Barbuda",
		"it": "Antigua e Barbuda",
		"es": "Antigua y Barbuda",
		"pl": "Antigua i Barbuda",
		"zh-cn": "安提瓜和巴布达"
	},
	"Chad": {
		"en": "Chad",
		"de": "Tschad",
		"ru": "Чад",
		"pt": "Chade",
		"nl": "Tsjaad",
		"fr": "Tchad",
		"it": "Chad",
		"es": "Chad",
		"pl": "Czad",
		"zh-cn": "乍得"
	},
	"Djibouti": {
		"en": "Djibouti",
		"de": "Dschibuti",
		"ru": "Джибути",
		"pt": "Djibuti",
		"nl": "Djibouti",
		"fr": "Djibouti",
		"it": "Gibuti",
		"es": "Djibouti",
		"pl": "Dżibuti",
		"zh-cn": "吉布地"
	},
	"Eritrea": {
		"en": "Eritrea",
		"de": "Eritrea",
		"ru": "Эритрея",
		"pt": "Eritreia",
		"nl": "Eritrea",
		"fr": "Érythrée",
		"it": "l'Eritrea",
		"es": "Eritrea",
		"pl": "Erytrea",
		"zh-cn": "厄立特里亚"
	},
	"Gambia": {
		"en": "Gambia",
		"de": "Gambia",
		"ru": "Гамбия",
		"pt": "Gâmbia",
		"nl": "Gambia",
		"fr": "Gambie",
		"it": "Gambia",
		"es": "Gambia",
		"pl": "Gambia",
		"zh-cn": "冈比亚"
	},
	"Vatican City": {
		"en": "Vatican City",
		"de": "Vatikanstadt",
		"ru": "Ватикан",
		"pt": "Cidade do Vaticano",
		"nl": "Vaticaanstad",
		"fr": "Cité du Vatican",
		"it": "Città del Vaticano",
		"es": "Ciudad del Vaticano",
		"pl": "Watykan",
		"zh-cn": "梵蒂冈城"
	},
	"Montserrat": {
		"en": "Montserrat",
		"de": "Montserrat",
		"ru": "Монсеррат",
		"pt": "Montserrat",
		"nl": "Montserrat",
		"fr": "Montserrat",
		"it": "Montserrat",
		"es": "Montserrat",
		"pl": "Montserrat",
		"zh-cn": "蒙特塞拉特"
	},
	"Papua New Guinea": {
		"en": "Papua New Guinea",
		"de": "Papua Neu-Guinea",
		"ru": "Папуа - Новая Гвинея",
		"pt": "Papua Nova Guiné",
		"nl": "Papoea-Nieuw-Guinea",
		"fr": "Papouasie Nouvelle Guinée",
		"it": "Papua Nuova Guinea",
		"es": "Papúa Nueva Guinea",
		"pl": "Papua Nowa Gwinea",
		"zh-cn": "巴布亚新几内亚"
	},
	"St. Vincent Grenadines": {
		"en": "St. Vincent Grenadines",
		"de": "St. Vincent Grenadinen",
		"ru": "Сент-Винсент Гренадины",
		"pt": "São Vicente e Granadinas",
		"nl": "St. Vincent Grenadines",
		"fr": "Saint-Vincent-Grenadines",
		"it": "Saint Vincent Grenadine",
		"es": "San Vicente Granadinas",
		"pl": "Saint Vincent Grenadyny",
		"zh-cn": "圣文森特格林纳丁斯"
	},
	"Sint Maarten": {
		"en": "Sint Maarten",
		"de": "Sint Maarten",
		"ru": "Синт-Мартен",
		"pt": "Sint Maarten",
		"nl": "Sint Maarten",
		"fr": "Sint Maarten",
		"it": "Sint Maarten",
		"es": "Sint Maarten",
		"pl": "Sint Maarten",
		"zh-cn": "圣马丁"
	},
	"Somalia": {
		"en": "Somalia",
		"de": "Somalia",
		"ru": "Сомали",
		"pt": "Somália",
		"nl": "Somalië",
		"fr": "Somalie",
		"it": "Somalia",
		"es": "Somalia",
		"pl": "Somali",
		"zh-cn": "索马里"
	},
	"Timor-Leste": {
		"en": "Timor-Leste",
		"de": "Timor-Leste",
		"ru": "Восточный Тимор",
		"pt": "Timor-Leste",
		"nl": "Oost-Timor",
		"fr": "Timor-Leste",
		"it": "Timor Est",
		"es": "Timor-Leste",
		"pl": "Timor Wschodni",
		"zh-cn": "东帝汶"
	},
	"Uganda": {
		"en": "Uganda",
		"de": "Uganda",
		"ru": "Уганда",
		"pt": "Uganda",
		"nl": "Oeganda",
		"fr": "Ouganda",
		"it": "Uganda",
		"es": "Uganda",
		"pl": "Uganda",
		"zh-cn": "乌干达"
	}
};
